### ISSUE TITLE
Smartphone and chat button

### ISSUE THREAD

**Issue by jjsarton** [jech/galene#231]
The chat symbol is placed via css 30px at the right. On some circumstance, dependant from used smartphone, the close video  and chat symbol overlap a little bit. Increasing the  css value to .collapse-video { right: 70px; } fix this.

See screenshot below:

![Screenshot 2024-11-16 at 10-22-26 Aps](https://github.com/user-attachments/assets/06225403-8633-4720-bdbd-5a6c45be151b)

If the value for the placement at the right value is modified as stated above the chat button will be placed below the Mike symbol.

If we have: ".collapse-video { right: calc(100vw - 48px); }" the chat symbol will be placed at the left of the video cantainer.

**Comment by jech** [comment]
Do you want to send a pull request, so that you can be properly credited in the git history?

**Comment by jjsarton** [comment]
I don't need to be credited.

**Comment by jech** [comment]
Fixed in 9503e332b6ca020882d11283108c328a198d1a2c, thanks.

**Comment by TheNomad11** [comment]
Hi @jech I still cannot see the chat button when connecting via my mobile phone. I tried it on your demo. I sent a message and on my mobile I was not able to see it. It becomes visable when I deactivate the video. It seems the video is covering the chat

**Comment by jech** [comment]
Yes, the mobile version needs work.  Could you please file an issue?

**Comment by TheNomad11** [comment]
done! https://github.com/jech/galene/issues/255

**Comment by jech** [comment]
I've reverted this patch, since it caused the chat button to disappear, as indicated in #255.
